# https://kodiakhq.com
version = 1

# https://kodiakhq.com/docs/recipes#adding-pull-request-approvals-to-dependabot-pull-requests
[approve]
# NOTE: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]

# If using `update.always`, add dependabot to the blacklist to allow
# dependabot to update and close stale dependency upgrades.
[update]
ignored_usernames = ["dependabot"]

[merge]
# Workaround for kodiak removing the automerge label, which causes it not to
# automerge dependabot PRs with conflicts:
# https://github.com/chdsbd/kodiak/issues/492#issuecomment-675797416
notify_on_conflict = false
